apiVersion: apps/v1
kind: Deployment
metadata:
  name: yash-practice-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yash-practice-backend-gcpapp
  template:
    metadata:
      labels:
        app: yash-practice-backend-gcpapp
    spec:
      containers:
      - name: yash-practice-app-container
        image: us-central1-docker.pkg.dev/wide-empire-206023/yash-practice-repo/yash-practice-app:latest
        ports:
        - containerPort: 8088

